spring.application.name=Package
spring.datasource.url=jdbc:postgresql://localhost:5432/GestionPackagePI
spring.datasource.username=postgres
spring.datasource.password=0000

server.port=8085
#EUREKA_REGISTERY
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG