CREATE DATABASE "GestionUserPI";
CREATE DATABASE "GestionAppointPI";
CREATE DATABASE "QuizPI";
CREATE DATABASE "GestionPackagePI";
CREATE DATABASE "DiscussionPI";
CREATE DATABASE "CoursePI";
CREATE DATABASE "ClubEventPI";