spring.application.name=Package
spring.datasource.url=jdbc:postgresql://localhost:5432/GestionPackagePI
spring.datasource.username=postgres
spring.datasource.password=0000
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=package-service

server.port=8085
#EUREKA_REGISTERY
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Flouci v2
stripe.secret.key=sk_test_51TKFwmPGtpP2NuWMVQccdpHfQoK2ZvIt59DmKHildA58zA1voiKC5z52mRKqYp1Id1HODX5Ec3KaP2BnUJMkNY2000VEfKDGTP
stripe.webhook.secret=whsec_881409d297f3a01a7b6a5e5d9a84965e7254933a54e5425b82ed7b89d781f0f5
flouci.public-key=d9e0dee3-fa42-4b23-8caa-5b991051c659
flouci.private-key=5cb6f89b-865a-4bd1-89a5-136a4f26409e
flouci.developer-tracking-prefix=PAY_cac816c5-d7a5-492e-9a06-c4272b9f969b
flouci.accept-card=true
flouci.session-timeout-secs=1200

# IMPORTANT: put FRONTEND URLs (Angular) for redirects
app.frontend-url=http://localhost:4200