spring.application.name=Quiz
spring.datasource.url=jdbc:postgresql://localhost:5432/GestionUserPI
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8056
#EUREKA_REGISTERY
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
server.name=http://localhost:4200
spring.jpa.open-in-view=false
# application.properties
spring.security.user.name=   # vide
spring.security.user.password=  # vide
spring.main.allow-bean-definition-overriding=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chahabsarah@gmail.com
spring.mail.password=lqfx slyr mrol gzml
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true