package tn.spring.user.Enums;

public enum NotificationType {
    REPORT_CREATED,
    REPORT_ASSIGNED,
    REPORT_STATUS_CHANGED,
    REPORT_COMMENT_ADDED,
    DISCUSSION_POST_CREATED,
    DISCUSSION_COMMENT_ADDED,
    DISCUSSION_REACTION_ADDED,
    SYSTEM_ALERT
}
